languageCode = "en-us"
title = "Russ Starr"
baseurl = "http://russstarr.github.io/"
theme = "prologue"

[params]
  name = "Russ Starr"
  description = "Cloud Engineer"
  copyright = "Russ Starr."

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/Russ_Starr"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/russix"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/russStarr"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/russstarr/"

# Portfolio column one

[[params.portfolio1]]
  title = "VMworld 2017: NET1338BU - VMware Integrated OpenStack and NSX Integration Deep Dive"
  alt = ""
  source = "img/vmworld2017.png"
  url = "http://media.licdn.com/embeds/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fz92YNlzAlEo%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dz92YNlzAlEo&amp;type=text%2Fhtml&amp;schema=youtube"

[[params.portfolio1]]
  title = "Cerner DevCon 2017: Web scale principles for Network Automation"
  alt = ""
  source = "img/webscale.png"
  url = "https://www.slideshare.net/secret/ACFES3RnFWKVM8"

# Portfolio column two

[[params.portfolio2]]
  title = "NetDevOps: Automation on Bare Metal Switches"
  alt = ""
  source = "img/netdevops.jpg"
  url = "https://raw.githubusercontent.com/kwitherstine/devopsmeetup_kc/master/DevOpsMeetup-KC-merged.pdf"

[[params.portfolio2]]
  title = "KC Network Programmability Meetup - Python netaddr Examples"
  alt = ""
  source = "img/netaddr.png"
  url = "https://www.slideshare.net/secret/spIZNVqVX3Pgl7"

# Portfolio column 3

[[params.portfolio3]]
  title = "OpenStack Summit Austin 2016 - Split Brain: Overlays as seen by Linux vs Networking folks"
  alt = ""
  source = "img/openstacksummit.png"
  url = "https://www.openstack.org/videos/summits/austin-2016/split-brain-overlays-as-seen-by-linux-vs-networking-folks"


# Tech Community column one

[[params.techcommunity1]]
  title = "Meetup"
  alt = ""
  source = "img/meetup.png"
  url = "https://www.meetup.com/members/73973752/"

[[params.techcommunity1]]
  title = "GitHub"
  alt = ""
  source = "img/github.jpg"
  url = "https://github.com/russStarr"

# Tech Community column two

[[params.techcommunity2]]
  title = "GitLab"
  alt = ""
  source = "img/gitlab.png"
  url = "https://gitlab.com/russStarr"

[[params.techcommunity2]]
  title = "Pluralsight"
  alt = ""
  source = "img/pluralsight.jpg"
  url = "https://app.pluralsight.com/profile/russstarr"

# Tech Community column 3

[[params.techcommunity3]]
  title = "Stack Overflow"
  alt = ""
  source = "img/stackoverflow.png"
  url = "https://stackoverflow.com/users/8413949/russ-starr"




# Gaming column one

[[params.gaming1]]
  title = "Steam"
  alt = ""
  gamertag = "destroyareazero"
  source = "img/steam.png"
  url = "https://steamcommunity.com/id/destroyareazero"

[[params.gaming1]]
  title = "Origin"
  alt = ""
  gamertag = "trendkc"
  source = "img/origin.png"
  url = "https://myaccount.ea.com/"

# Gaming column two

[[params.gaming2]]
  title = "Xbox"
  alt = ""
  gamertag = "trend9420"
  source = "img/xbox.png"
  url = "https://account.xbox.com/Profile?Gamertag=trend9420"

[[params.gaming2]]
  title = "Epic"
  alt = ""
  gamertag = "StarrDotStarr"
  source = "img/epic.png"
  url = "https://www.epicgames.com/account"

# Gaming column three

[[params.gaming3]]
  title = "Battle Net"
  alt = ""
  gamertag = "trend#11688"
  source = "img/blizzard.png"
  url = "https://account.blizzard.com/overview"

[[params.gaming3]]
  title = "Nintendo"
  alt = ""
  gamertag = "Russix"
  source = "img/nintendo.png"
  url = "https://accounts.nintendo.com/"

# Gaming column four

[[params.gaming4]]
  title = "Overwatch"
  alt = ""
  gamertag = "trend#11688"
  source = "img/overwatch.png"
  url = "https://playoverwatch.com/en-us/career/pc/trend-11688"

# Gaming column five

[[params.gaming5]]
  title = "Activision"
  alt = ""
  gamertag = "trend#9700475"
  source = "img/activision.svg"
  url = "https://s.activision.com/activision/profile"

# Gaming column six

[[params.gaming6]]
  title = "Twitch"
  alt = ""
  gamertag = "ephemeruss"
  source = "img/twitch.png"
  url = "https://www.twitch.tv/ephemeruss"

